[package]
name = "prediction_market"
version = "0.1.0"
edition = "2021"

[lib]
name = "prediction_market"
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "^0.30.1"
anchor-spl = "^0.30.1"



[features]
default = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
